#pragma once

#include "tatarus/types.hpp"

#include <array>
#include <vector>

namespace tatarus::neuro::vestibular {

struct VestibularConfig {
    double gravityMps2 = 9.80665;
    double canalAdaptationTauSeconds = 4.5;
    double otolithGravityTauSeconds = 0.75;
    double maximumAngularVelocityRadPerSecond = 6.0;
    double maximumLinearAccelerationG = 2.5;
    double vorGain = 0.92;

    void validate() const;
};

struct VestibularPercept {
    bool available = false;
    // Three semicircular canal population outputs: roll, pitch, yaw.
    std::array<double, 3> canal{};
    // Estimated gravity vector in sensor/body coordinates.
    std::array<double, 3> gravity{};
    // Translation-specific acceleration after gravity separation.
    std::array<double, 3> linearAcceleration{};
    // Otolith tilt/gravity direction, normalized to approximately [-1, 1].
    std::array<double, 3> tilt{};
    // Compensatory eye angular velocity generated by the VOR in deg/s.
    std::array<double, 3> vorEyeVelocityDegPerSecond{};
    // Bounded afferent population code delivered as vestibular nerve events.
    std::vector<double> vestibularNerveEvents;
    double angularMotion = 0.0;
    double linearMotion = 0.0;
    double gravityConfidence = 0.0;
};

class VestibularSystem {
public:
    explicit VestibularSystem(VestibularConfig config = {});

    [[nodiscard]] VestibularPercept step(const ImuState& imu, double dtSeconds);
    void reset() noexcept;

    [[nodiscard]] const VestibularConfig& config() const noexcept { return config_; }

private:
    VestibularConfig config_;
    std::array<double, 3> canalAdaptation_{};
    std::array<double, 3> gravityEstimate_{};
    bool gravityInitialized_ = false;
};

} // namespace tatarus::neuro::vestibular
